### ISSUE TITLE
关于依赖项@hapi/joi被弃用这件事

### ISSUE THREAD

**Issue by TuJinSAMA** [liulongbin1314/express-joi#1]
刘老师您好，使用包的过程中，发现在npm官网中依赖项@hapi/joi包的首页显示该包已经被弃用，而作者留言是这样的： `Switch to 'npm install joi'`，仔细研读了您的源码后，发现新版本的joi并没有改变包内所使用的方法，所以个人认为是不是可以将依赖项换成最新的包，虽然不换依然可以实现功能就是了。
附相关链接：[https://www.npmjs.com/package/%40hapi/joi](url)

**Comment by liulongbin1314** [comment]
感谢反馈，目前 @escook/express-joi 1.1.1 的版本中已经弃用了 @hapi/joi，切换到了 joi 。
